// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: lesson9.proto
// Protobuf Java Version: 4.28.3

package com.cnebrera.uc3.tech.lesson9.proto;

public final class Lesson9 {
  private Lesson9() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      Lesson9.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InstrumentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Instrument)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * a int that identifies the instrument
     * </pre>
     *
     * <code>int32 instrumentId = 1;</code>
     * @return The instrumentId.
     */
    int getInstrumentId();

    /**
     * <pre>
     * human understood representation of the security
     * </pre>
     *
     * <code>string symbol = 2;</code>
     * @return The symbol.
     */
    java.lang.String getSymbol();
    /**
     * <pre>
     * human understood representation of the security
     * </pre>
     *
     * <code>string symbol = 2;</code>
     * @return The bytes for symbol.
     */
    com.google.protobuf.ByteString
        getSymbolBytes();
  }
  /**
   * <pre>
   * --- Equivalente a com.cnebrera.uc3.tech.lesson9.model.Instrument ---
   * </pre>
   *
   * Protobuf type {@code Instrument}
   */
  public static final class Instrument extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Instrument)
      InstrumentOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        Instrument.class.getName());
    }
    // Use Instrument.newBuilder() to construct.
    private Instrument(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Instrument() {
      symbol_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cnebrera.uc3.tech.lesson9.proto.Lesson9.internal_static_Instrument_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cnebrera.uc3.tech.lesson9.proto.Lesson9.internal_static_Instrument_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.class, com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.Builder.class);
    }

    public static final int INSTRUMENTID_FIELD_NUMBER = 1;
    private int instrumentId_ = 0;
    /**
     * <pre>
     * a int that identifies the instrument
     * </pre>
     *
     * <code>int32 instrumentId = 1;</code>
     * @return The instrumentId.
     */
    @java.lang.Override
    public int getInstrumentId() {
      return instrumentId_;
    }

    public static final int SYMBOL_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object symbol_ = "";
    /**
     * <pre>
     * human understood representation of the security
     * </pre>
     *
     * <code>string symbol = 2;</code>
     * @return The symbol.
     */
    @java.lang.Override
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * human understood representation of the security
     * </pre>
     *
     * <code>string symbol = 2;</code>
     * @return The bytes for symbol.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (instrumentId_ != 0) {
        output.writeInt32(1, instrumentId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(symbol_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, symbol_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (instrumentId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, instrumentId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(symbol_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, symbol_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument)) {
        return super.equals(obj);
      }
      com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument other = (com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument) obj;

      if (getInstrumentId()
          != other.getInstrumentId()) return false;
      if (!getSymbol()
          .equals(other.getSymbol())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INSTRUMENTID_FIELD_NUMBER;
      hash = (53 * hash) + getInstrumentId();
      hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
      hash = (53 * hash) + getSymbol().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * --- Equivalente a com.cnebrera.uc3.tech.lesson9.model.Instrument ---
     * </pre>
     *
     * Protobuf type {@code Instrument}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Instrument)
        com.cnebrera.uc3.tech.lesson9.proto.Lesson9.InstrumentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cnebrera.uc3.tech.lesson9.proto.Lesson9.internal_static_Instrument_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cnebrera.uc3.tech.lesson9.proto.Lesson9.internal_static_Instrument_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.class, com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.Builder.class);
      }

      // Construct using com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        instrumentId_ = 0;
        symbol_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cnebrera.uc3.tech.lesson9.proto.Lesson9.internal_static_Instrument_descriptor;
      }

      @java.lang.Override
      public com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument getDefaultInstanceForType() {
        return com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.getDefaultInstance();
      }

      @java.lang.Override
      public com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument build() {
        com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument buildPartial() {
        com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument result = new com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.instrumentId_ = instrumentId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.symbol_ = symbol_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument) {
          return mergeFrom((com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument other) {
        if (other == com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.getDefaultInstance()) return this;
        if (other.getInstrumentId() != 0) {
          setInstrumentId(other.getInstrumentId());
        }
        if (!other.getSymbol().isEmpty()) {
          symbol_ = other.symbol_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                instrumentId_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                symbol_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int instrumentId_ ;
      /**
       * <pre>
       * a int that identifies the instrument
       * </pre>
       *
       * <code>int32 instrumentId = 1;</code>
       * @return The instrumentId.
       */
      @java.lang.Override
      public int getInstrumentId() {
        return instrumentId_;
      }
      /**
       * <pre>
       * a int that identifies the instrument
       * </pre>
       *
       * <code>int32 instrumentId = 1;</code>
       * @param value The instrumentId to set.
       * @return This builder for chaining.
       */
      public Builder setInstrumentId(int value) {

        instrumentId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * a int that identifies the instrument
       * </pre>
       *
       * <code>int32 instrumentId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearInstrumentId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        instrumentId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object symbol_ = "";
      /**
       * <pre>
       * human understood representation of the security
       * </pre>
       *
       * <code>string symbol = 2;</code>
       * @return The symbol.
       */
      public java.lang.String getSymbol() {
        java.lang.Object ref = symbol_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          symbol_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * human understood representation of the security
       * </pre>
       *
       * <code>string symbol = 2;</code>
       * @return The bytes for symbol.
       */
      public com.google.protobuf.ByteString
          getSymbolBytes() {
        java.lang.Object ref = symbol_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          symbol_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * human understood representation of the security
       * </pre>
       *
       * <code>string symbol = 2;</code>
       * @param value The symbol to set.
       * @return This builder for chaining.
       */
      public Builder setSymbol(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        symbol_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * human understood representation of the security
       * </pre>
       *
       * <code>string symbol = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSymbol() {
        symbol_ = getDefaultInstance().getSymbol();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * human understood representation of the security
       * </pre>
       *
       * <code>string symbol = 2;</code>
       * @param value The bytes for symbol to set.
       * @return This builder for chaining.
       */
      public Builder setSymbolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        symbol_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Instrument)
    }

    // @@protoc_insertion_point(class_scope:Instrument)
    private static final com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument();
    }

    public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Instrument>
        PARSER = new com.google.protobuf.AbstractParser<Instrument>() {
      @java.lang.Override
      public Instrument parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Instrument> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Instrument> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReferenceDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReferenceData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * a int that identifies the market
     * </pre>
     *
     * <code>int32 marketId = 1;</code>
     * @return The marketId.
     */
    int getMarketId();

    /**
     * <pre>
     * a String with the algorithm identifier
     * </pre>
     *
     * <code>string algorithmIdentifier = 2;</code>
     * @return The algorithmIdentifier.
     */
    java.lang.String getAlgorithmIdentifier();
    /**
     * <pre>
     * a String with the algorithm identifier
     * </pre>
     *
     * <code>string algorithmIdentifier = 2;</code>
     * @return The bytes for algorithmIdentifier.
     */
    com.google.protobuf.ByteString
        getAlgorithmIdentifierBytes();

    /**
     * <pre>
     * lista de instrumentos -&gt; en Java habrá métodos addInstrument(...)
     * </pre>
     *
     * <code>repeated .Instrument instrument = 3;</code>
     */
    java.util.List<com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument> 
        getInstrumentList();
    /**
     * <pre>
     * lista de instrumentos -&gt; en Java habrá métodos addInstrument(...)
     * </pre>
     *
     * <code>repeated .Instrument instrument = 3;</code>
     */
    com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument getInstrument(int index);
    /**
     * <pre>
     * lista de instrumentos -&gt; en Java habrá métodos addInstrument(...)
     * </pre>
     *
     * <code>repeated .Instrument instrument = 3;</code>
     */
    int getInstrumentCount();
    /**
     * <pre>
     * lista de instrumentos -&gt; en Java habrá métodos addInstrument(...)
     * </pre>
     *
     * <code>repeated .Instrument instrument = 3;</code>
     */
    java.util.List<? extends com.cnebrera.uc3.tech.lesson9.proto.Lesson9.InstrumentOrBuilder> 
        getInstrumentOrBuilderList();
    /**
     * <pre>
     * lista de instrumentos -&gt; en Java habrá métodos addInstrument(...)
     * </pre>
     *
     * <code>repeated .Instrument instrument = 3;</code>
     */
    com.cnebrera.uc3.tech.lesson9.proto.Lesson9.InstrumentOrBuilder getInstrumentOrBuilder(
        int index);
  }
  /**
   * <pre>
   * --- Equivalente a com.cnebrera.uc3.tech.lesson9.model.ReferenceData ---
   * </pre>
   *
   * Protobuf type {@code ReferenceData}
   */
  public static final class ReferenceData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ReferenceData)
      ReferenceDataOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        ReferenceData.class.getName());
    }
    // Use ReferenceData.newBuilder() to construct.
    private ReferenceData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ReferenceData() {
      algorithmIdentifier_ = "";
      instrument_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cnebrera.uc3.tech.lesson9.proto.Lesson9.internal_static_ReferenceData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cnebrera.uc3.tech.lesson9.proto.Lesson9.internal_static_ReferenceData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData.class, com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData.Builder.class);
    }

    public static final int MARKETID_FIELD_NUMBER = 1;
    private int marketId_ = 0;
    /**
     * <pre>
     * a int that identifies the market
     * </pre>
     *
     * <code>int32 marketId = 1;</code>
     * @return The marketId.
     */
    @java.lang.Override
    public int getMarketId() {
      return marketId_;
    }

    public static final int ALGORITHMIDENTIFIER_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object algorithmIdentifier_ = "";
    /**
     * <pre>
     * a String with the algorithm identifier
     * </pre>
     *
     * <code>string algorithmIdentifier = 2;</code>
     * @return The algorithmIdentifier.
     */
    @java.lang.Override
    public java.lang.String getAlgorithmIdentifier() {
      java.lang.Object ref = algorithmIdentifier_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        algorithmIdentifier_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * a String with the algorithm identifier
     * </pre>
     *
     * <code>string algorithmIdentifier = 2;</code>
     * @return The bytes for algorithmIdentifier.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAlgorithmIdentifierBytes() {
      java.lang.Object ref = algorithmIdentifier_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        algorithmIdentifier_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INSTRUMENT_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private java.util.List<com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument> instrument_;
    /**
     * <pre>
     * lista de instrumentos -&gt; en Java habrá métodos addInstrument(...)
     * </pre>
     *
     * <code>repeated .Instrument instrument = 3;</code>
     */
    @java.lang.Override
    public java.util.List<com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument> getInstrumentList() {
      return instrument_;
    }
    /**
     * <pre>
     * lista de instrumentos -&gt; en Java habrá métodos addInstrument(...)
     * </pre>
     *
     * <code>repeated .Instrument instrument = 3;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.cnebrera.uc3.tech.lesson9.proto.Lesson9.InstrumentOrBuilder> 
        getInstrumentOrBuilderList() {
      return instrument_;
    }
    /**
     * <pre>
     * lista de instrumentos -&gt; en Java habrá métodos addInstrument(...)
     * </pre>
     *
     * <code>repeated .Instrument instrument = 3;</code>
     */
    @java.lang.Override
    public int getInstrumentCount() {
      return instrument_.size();
    }
    /**
     * <pre>
     * lista de instrumentos -&gt; en Java habrá métodos addInstrument(...)
     * </pre>
     *
     * <code>repeated .Instrument instrument = 3;</code>
     */
    @java.lang.Override
    public com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument getInstrument(int index) {
      return instrument_.get(index);
    }
    /**
     * <pre>
     * lista de instrumentos -&gt; en Java habrá métodos addInstrument(...)
     * </pre>
     *
     * <code>repeated .Instrument instrument = 3;</code>
     */
    @java.lang.Override
    public com.cnebrera.uc3.tech.lesson9.proto.Lesson9.InstrumentOrBuilder getInstrumentOrBuilder(
        int index) {
      return instrument_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (marketId_ != 0) {
        output.writeInt32(1, marketId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(algorithmIdentifier_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, algorithmIdentifier_);
      }
      for (int i = 0; i < instrument_.size(); i++) {
        output.writeMessage(3, instrument_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (marketId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, marketId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(algorithmIdentifier_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, algorithmIdentifier_);
      }
      for (int i = 0; i < instrument_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, instrument_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData)) {
        return super.equals(obj);
      }
      com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData other = (com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData) obj;

      if (getMarketId()
          != other.getMarketId()) return false;
      if (!getAlgorithmIdentifier()
          .equals(other.getAlgorithmIdentifier())) return false;
      if (!getInstrumentList()
          .equals(other.getInstrumentList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MARKETID_FIELD_NUMBER;
      hash = (53 * hash) + getMarketId();
      hash = (37 * hash) + ALGORITHMIDENTIFIER_FIELD_NUMBER;
      hash = (53 * hash) + getAlgorithmIdentifier().hashCode();
      if (getInstrumentCount() > 0) {
        hash = (37 * hash) + INSTRUMENT_FIELD_NUMBER;
        hash = (53 * hash) + getInstrumentList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * --- Equivalente a com.cnebrera.uc3.tech.lesson9.model.ReferenceData ---
     * </pre>
     *
     * Protobuf type {@code ReferenceData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReferenceData)
        com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cnebrera.uc3.tech.lesson9.proto.Lesson9.internal_static_ReferenceData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cnebrera.uc3.tech.lesson9.proto.Lesson9.internal_static_ReferenceData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData.class, com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData.Builder.class);
      }

      // Construct using com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        marketId_ = 0;
        algorithmIdentifier_ = "";
        if (instrumentBuilder_ == null) {
          instrument_ = java.util.Collections.emptyList();
        } else {
          instrument_ = null;
          instrumentBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cnebrera.uc3.tech.lesson9.proto.Lesson9.internal_static_ReferenceData_descriptor;
      }

      @java.lang.Override
      public com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData getDefaultInstanceForType() {
        return com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData.getDefaultInstance();
      }

      @java.lang.Override
      public com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData build() {
        com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData buildPartial() {
        com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData result = new com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData result) {
        if (instrumentBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0)) {
            instrument_ = java.util.Collections.unmodifiableList(instrument_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.instrument_ = instrument_;
        } else {
          result.instrument_ = instrumentBuilder_.build();
        }
      }

      private void buildPartial0(com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.marketId_ = marketId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.algorithmIdentifier_ = algorithmIdentifier_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData) {
          return mergeFrom((com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData other) {
        if (other == com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData.getDefaultInstance()) return this;
        if (other.getMarketId() != 0) {
          setMarketId(other.getMarketId());
        }
        if (!other.getAlgorithmIdentifier().isEmpty()) {
          algorithmIdentifier_ = other.algorithmIdentifier_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (instrumentBuilder_ == null) {
          if (!other.instrument_.isEmpty()) {
            if (instrument_.isEmpty()) {
              instrument_ = other.instrument_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureInstrumentIsMutable();
              instrument_.addAll(other.instrument_);
            }
            onChanged();
          }
        } else {
          if (!other.instrument_.isEmpty()) {
            if (instrumentBuilder_.isEmpty()) {
              instrumentBuilder_.dispose();
              instrumentBuilder_ = null;
              instrument_ = other.instrument_;
              bitField0_ = (bitField0_ & ~0x00000004);
              instrumentBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getInstrumentFieldBuilder() : null;
            } else {
              instrumentBuilder_.addAllMessages(other.instrument_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                marketId_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                algorithmIdentifier_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument m =
                    input.readMessage(
                        com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.parser(),
                        extensionRegistry);
                if (instrumentBuilder_ == null) {
                  ensureInstrumentIsMutable();
                  instrument_.add(m);
                } else {
                  instrumentBuilder_.addMessage(m);
                }
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int marketId_ ;
      /**
       * <pre>
       * a int that identifies the market
       * </pre>
       *
       * <code>int32 marketId = 1;</code>
       * @return The marketId.
       */
      @java.lang.Override
      public int getMarketId() {
        return marketId_;
      }
      /**
       * <pre>
       * a int that identifies the market
       * </pre>
       *
       * <code>int32 marketId = 1;</code>
       * @param value The marketId to set.
       * @return This builder for chaining.
       */
      public Builder setMarketId(int value) {

        marketId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * a int that identifies the market
       * </pre>
       *
       * <code>int32 marketId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMarketId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        marketId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object algorithmIdentifier_ = "";
      /**
       * <pre>
       * a String with the algorithm identifier
       * </pre>
       *
       * <code>string algorithmIdentifier = 2;</code>
       * @return The algorithmIdentifier.
       */
      public java.lang.String getAlgorithmIdentifier() {
        java.lang.Object ref = algorithmIdentifier_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          algorithmIdentifier_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * a String with the algorithm identifier
       * </pre>
       *
       * <code>string algorithmIdentifier = 2;</code>
       * @return The bytes for algorithmIdentifier.
       */
      public com.google.protobuf.ByteString
          getAlgorithmIdentifierBytes() {
        java.lang.Object ref = algorithmIdentifier_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          algorithmIdentifier_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * a String with the algorithm identifier
       * </pre>
       *
       * <code>string algorithmIdentifier = 2;</code>
       * @param value The algorithmIdentifier to set.
       * @return This builder for chaining.
       */
      public Builder setAlgorithmIdentifier(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        algorithmIdentifier_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * a String with the algorithm identifier
       * </pre>
       *
       * <code>string algorithmIdentifier = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAlgorithmIdentifier() {
        algorithmIdentifier_ = getDefaultInstance().getAlgorithmIdentifier();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * a String with the algorithm identifier
       * </pre>
       *
       * <code>string algorithmIdentifier = 2;</code>
       * @param value The bytes for algorithmIdentifier to set.
       * @return This builder for chaining.
       */
      public Builder setAlgorithmIdentifierBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        algorithmIdentifier_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.util.List<com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument> instrument_ =
        java.util.Collections.emptyList();
      private void ensureInstrumentIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          instrument_ = new java.util.ArrayList<com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument>(instrument_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument, com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.Builder, com.cnebrera.uc3.tech.lesson9.proto.Lesson9.InstrumentOrBuilder> instrumentBuilder_;

      /**
       * <pre>
       * lista de instrumentos -&gt; en Java habrá métodos addInstrument(...)
       * </pre>
       *
       * <code>repeated .Instrument instrument = 3;</code>
       */
      public java.util.List<com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument> getInstrumentList() {
        if (instrumentBuilder_ == null) {
          return java.util.Collections.unmodifiableList(instrument_);
        } else {
          return instrumentBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * lista de instrumentos -&gt; en Java habrá métodos addInstrument(...)
       * </pre>
       *
       * <code>repeated .Instrument instrument = 3;</code>
       */
      public int getInstrumentCount() {
        if (instrumentBuilder_ == null) {
          return instrument_.size();
        } else {
          return instrumentBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * lista de instrumentos -&gt; en Java habrá métodos addInstrument(...)
       * </pre>
       *
       * <code>repeated .Instrument instrument = 3;</code>
       */
      public com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument getInstrument(int index) {
        if (instrumentBuilder_ == null) {
          return instrument_.get(index);
        } else {
          return instrumentBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * lista de instrumentos -&gt; en Java habrá métodos addInstrument(...)
       * </pre>
       *
       * <code>repeated .Instrument instrument = 3;</code>
       */
      public Builder setInstrument(
          int index, com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument value) {
        if (instrumentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInstrumentIsMutable();
          instrument_.set(index, value);
          onChanged();
        } else {
          instrumentBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * lista de instrumentos -&gt; en Java habrá métodos addInstrument(...)
       * </pre>
       *
       * <code>repeated .Instrument instrument = 3;</code>
       */
      public Builder setInstrument(
          int index, com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.Builder builderForValue) {
        if (instrumentBuilder_ == null) {
          ensureInstrumentIsMutable();
          instrument_.set(index, builderForValue.build());
          onChanged();
        } else {
          instrumentBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * lista de instrumentos -&gt; en Java habrá métodos addInstrument(...)
       * </pre>
       *
       * <code>repeated .Instrument instrument = 3;</code>
       */
      public Builder addInstrument(com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument value) {
        if (instrumentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInstrumentIsMutable();
          instrument_.add(value);
          onChanged();
        } else {
          instrumentBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * lista de instrumentos -&gt; en Java habrá métodos addInstrument(...)
       * </pre>
       *
       * <code>repeated .Instrument instrument = 3;</code>
       */
      public Builder addInstrument(
          int index, com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument value) {
        if (instrumentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInstrumentIsMutable();
          instrument_.add(index, value);
          onChanged();
        } else {
          instrumentBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * lista de instrumentos -&gt; en Java habrá métodos addInstrument(...)
       * </pre>
       *
       * <code>repeated .Instrument instrument = 3;</code>
       */
      public Builder addInstrument(
          com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.Builder builderForValue) {
        if (instrumentBuilder_ == null) {
          ensureInstrumentIsMutable();
          instrument_.add(builderForValue.build());
          onChanged();
        } else {
          instrumentBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * lista de instrumentos -&gt; en Java habrá métodos addInstrument(...)
       * </pre>
       *
       * <code>repeated .Instrument instrument = 3;</code>
       */
      public Builder addInstrument(
          int index, com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.Builder builderForValue) {
        if (instrumentBuilder_ == null) {
          ensureInstrumentIsMutable();
          instrument_.add(index, builderForValue.build());
          onChanged();
        } else {
          instrumentBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * lista de instrumentos -&gt; en Java habrá métodos addInstrument(...)
       * </pre>
       *
       * <code>repeated .Instrument instrument = 3;</code>
       */
      public Builder addAllInstrument(
          java.lang.Iterable<? extends com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument> values) {
        if (instrumentBuilder_ == null) {
          ensureInstrumentIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, instrument_);
          onChanged();
        } else {
          instrumentBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * lista de instrumentos -&gt; en Java habrá métodos addInstrument(...)
       * </pre>
       *
       * <code>repeated .Instrument instrument = 3;</code>
       */
      public Builder clearInstrument() {
        if (instrumentBuilder_ == null) {
          instrument_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          instrumentBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * lista de instrumentos -&gt; en Java habrá métodos addInstrument(...)
       * </pre>
       *
       * <code>repeated .Instrument instrument = 3;</code>
       */
      public Builder removeInstrument(int index) {
        if (instrumentBuilder_ == null) {
          ensureInstrumentIsMutable();
          instrument_.remove(index);
          onChanged();
        } else {
          instrumentBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * lista de instrumentos -&gt; en Java habrá métodos addInstrument(...)
       * </pre>
       *
       * <code>repeated .Instrument instrument = 3;</code>
       */
      public com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.Builder getInstrumentBuilder(
          int index) {
        return getInstrumentFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * lista de instrumentos -&gt; en Java habrá métodos addInstrument(...)
       * </pre>
       *
       * <code>repeated .Instrument instrument = 3;</code>
       */
      public com.cnebrera.uc3.tech.lesson9.proto.Lesson9.InstrumentOrBuilder getInstrumentOrBuilder(
          int index) {
        if (instrumentBuilder_ == null) {
          return instrument_.get(index);  } else {
          return instrumentBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * lista de instrumentos -&gt; en Java habrá métodos addInstrument(...)
       * </pre>
       *
       * <code>repeated .Instrument instrument = 3;</code>
       */
      public java.util.List<? extends com.cnebrera.uc3.tech.lesson9.proto.Lesson9.InstrumentOrBuilder> 
           getInstrumentOrBuilderList() {
        if (instrumentBuilder_ != null) {
          return instrumentBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(instrument_);
        }
      }
      /**
       * <pre>
       * lista de instrumentos -&gt; en Java habrá métodos addInstrument(...)
       * </pre>
       *
       * <code>repeated .Instrument instrument = 3;</code>
       */
      public com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.Builder addInstrumentBuilder() {
        return getInstrumentFieldBuilder().addBuilder(
            com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.getDefaultInstance());
      }
      /**
       * <pre>
       * lista de instrumentos -&gt; en Java habrá métodos addInstrument(...)
       * </pre>
       *
       * <code>repeated .Instrument instrument = 3;</code>
       */
      public com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.Builder addInstrumentBuilder(
          int index) {
        return getInstrumentFieldBuilder().addBuilder(
            index, com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.getDefaultInstance());
      }
      /**
       * <pre>
       * lista de instrumentos -&gt; en Java habrá métodos addInstrument(...)
       * </pre>
       *
       * <code>repeated .Instrument instrument = 3;</code>
       */
      public java.util.List<com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.Builder> 
           getInstrumentBuilderList() {
        return getInstrumentFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument, com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.Builder, com.cnebrera.uc3.tech.lesson9.proto.Lesson9.InstrumentOrBuilder> 
          getInstrumentFieldBuilder() {
        if (instrumentBuilder_ == null) {
          instrumentBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument, com.cnebrera.uc3.tech.lesson9.proto.Lesson9.Instrument.Builder, com.cnebrera.uc3.tech.lesson9.proto.Lesson9.InstrumentOrBuilder>(
                  instrument_,
                  ((bitField0_ & 0x00000004) != 0),
                  getParentForChildren(),
                  isClean());
          instrument_ = null;
        }
        return instrumentBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ReferenceData)
    }

    // @@protoc_insertion_point(class_scope:ReferenceData)
    private static final com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData();
    }

    public static com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReferenceData>
        PARSER = new com.google.protobuf.AbstractParser<ReferenceData>() {
      @java.lang.Override
      public ReferenceData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ReferenceData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReferenceData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.cnebrera.uc3.tech.lesson9.proto.Lesson9.ReferenceData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Instrument_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Instrument_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReferenceData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ReferenceData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rlesson9.proto\"2\n\nInstrument\022\024\n\014instrum" +
      "entId\030\001 \001(\005\022\016\n\006symbol\030\002 \001(\t\"_\n\rReference" +
      "Data\022\020\n\010marketId\030\001 \001(\005\022\033\n\023algorithmIdent" +
      "ifier\030\002 \001(\t\022\037\n\ninstrument\030\003 \003(\0132\013.Instru" +
      "mentB.\n#com.cnebrera.uc3.tech.lesson9.pr" +
      "otoB\007Lesson9b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Instrument_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Instrument_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Instrument_descriptor,
        new java.lang.String[] { "InstrumentId", "Symbol", });
    internal_static_ReferenceData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ReferenceData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ReferenceData_descriptor,
        new java.lang.String[] { "MarketId", "AlgorithmIdentifier", "Instrument", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
